# 1) Create source sound collection

This notebook includes the code to create the collection of sounds that will later be used as source material for our audio mosaicing application. The collection of sounds is created by defining a number of queries to be performed using the Freesound API and concatenanting the results of each query. A number of metadata fields are stored for each sound in the collection and saved into a Pandas DataFrame object and CSV file in disk. For each sound in the collection, we also download an OGG preview and store it in disk.

This notebook uses the `freesound` Python package for interacting with the Freesound API. The source code for this package can be found here: https://github.com/mtg/freesound-python. In this repository you'll find a Python script with [examples](https://github.com/MTG/freesound-python/blob/master/examples.py) to learn how to interact with the API. Nevertheless, if you are further interested in the Freesound API, check the [API documentation](http://freesound.org/docs/api/) which provides more information.

**NOTE**: A Freesound API key is provided in this notebook, but you should make a Freesound account and get your own key. You can get a key here: https://freesound.org/apiv2/apply/

In [10]:
%pip install essentia -q
%pip install git+https://github.com/mtg/freesound-python.git -q
from google.colab import drive
drive.mount('/content/drive')

Requirement already satisfied: essentia in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (2.1b6.dev1110)
Requirement already satisfied: numpy>=1.8.2 in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from essentia) (2.2.6)
Requirement already satisfied: six in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from essentia) (1.17.0)
Requirement already satisfied: pyyaml in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from essentia) (6.0.3)
Collecting git+https://github.com/mtg/freesound-python.git
  Cloning https://github.com/mtg/freesound-python.git to /private/var/folders/hg/08z3tgbj2cj4qdxty9pxbfgr0000gn/T/pip-req-build-c0vfg1nn
  Running command git clone --filter=blob:none --quiet https://github.com/mtg/freesound-python.git /private/var/folders/hg/08z3tgbj2cj4qdxty9pxbfgr0000gn/T/pip-req-build-c0vfg1nn
  Resolved https://github.com/mtg/freesound-python.git to commit 73cf6d14f7ce8174d943bdc78ff30f99878a5db8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests<3.0,>2.27 in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from freesound-python==1.1) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from requests<3.0,>2.27->freesound-python==1.1) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from requests<3.0,>2.27->freesound-python==1.1) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from requests<3.0,>2.27->freesound-python==1.1) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages (from requests<3.0,>2.27->freesound-python==1.1) (2026.5.20)

In [11]:
%cd /content

/Users/martinsssssss/Desktop/SMC/ACTSM/Block II/1. Sound Retrieval with Fresound/audio-mosaicing

/Users/martinsssssss/opt/anaconda3/envs/audio-mosaicing/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [15]:
import os
import pandas as pd
import numpy as np
import freesound
from IPython.display import display

FREESOUND_API_KEY = 'MWlym7kxqnyVRbmTtWJSRTCXlemiu4ocYZurgCkD'  # Please replace by your own Freesound API key
FILES_DIR = 'files'  # Place where to store the downloaded diles. Will be relative to the current folder.
DATAFRAME_FILENAME = 'dataframe.csv'  # File where we'll store the metadata of our sounds collection
FREESOUND_STORE_METADATA_FIELDS = ['id', 'name', 'username', 'previews', 'license', 'tags']  # Freesound metadata properties to store

freesound_client = freesound.FreesoundClient()
freesound_client.set_token(FREESOUND_API_KEY)
if not os.path.exists(FILES_DIR): os.mkdir(FILES_DIR)

In [16]:
# Define some util functions

def query_freesound(query, filter, num_results=10):
    """Queries freesound with the given query and filter values.
    If no filter is given, a default filter is added to only get sounds shorter than 30 seconds.
    """
    if filter is None:
        filter = 'duration:[0 TO 30]'  # Set default filter
    pager = freesound_client.search(
        query = query,
        filter = filter,
        fields = ','.join(FREESOUND_STORE_METADATA_FIELDS),
        group_by_pack = 1,
        page_size = num_results
    )
    return [sound for sound in pager]

def retrieve_sound_preview(sound, directory):
    """Download the high-quality OGG sound preview of a given Freesound sound object to the given directory.
    """
    return freesound.FSRequest.retrieve(
        sound.previews.preview_hq_ogg,
        freesound_client,
        os.path.join(directory, sound.previews.preview_hq_ogg.split('/')[-1])
    )

def make_pandas_record(sound):
    """Create a dictionary with the metadata that we want to store for each sound.
    """
    record = {key: sound.as_dict()[key] for key in FREESOUND_STORE_METADATA_FIELDS}
    del record['previews']  # Don't store previews dict in record
    record['freesound_id'] = record['id']  # Rename 'id' to 'freesound_id'
    del record['id']
    record['path'] = "files/" + sound.previews.preview_hq_ogg.split("/")[-1]  # Store path of downloaded file
    return record

In [14]:
# ── Collection 1: Dark Techno / Acid ─────────────────────────────────────────

# Our collection of sounds is made by appending the results of a number of different queries to freesound
# The query terms, query filters and the number of results per query are all defined here.
# Information about how to define filters can be found in the Freesound API documentation: https://freesound.org/docs/api/resources_apiv2.html#request-parameters-text-search-parameters
freesound_queries = [
    {
        'query': 'kick drum',
        'filter': 'duration:[0 TO 2]',
        'num_results': 15,
    },
    {
        'query': 'dark techno percussion',
        'filter': 'duration:[0 TO 2]',
        'num_results': 15,
    },
    {
        'query': 'industrial metal clang',
        'filter': 'duration:[0 TO 2]',
        'num_results': 10,
    },
    {
        'query': 'synthesizer bass dark',
        'filter': 'duration:[0 TO 3]',
        'num_results': 10,
    },
    {
        'query': 'noise drone dark',
        'filter': 'duration:[0 TO 3]',
        'num_results': 13,
    },
    {
        'query': 'acid bass 303',
        'filter': 'duration:[0 TO 3]',
        'num_results': 8,
    },
    {
        'query': 'hi-hat electronic',
        'filter': 'duration:[0 TO 1]',
        'num_results': 8,
    },
    {
        'query': 'clap snare electronic',
        'filter': 'duration:[0 TO 1]',
        'num_results': 8,
    },
]

# Do all queries and concatenate the results in a single list of sounds
sounds = sum([query_freesound(query['query'], query['filter'], query['num_results']) for query in freesound_queries],[])

# Download the sounds and save them to FILES_DIR folder
for count, sound in enumerate(sounds):
    print('Downloading sound with id {0} [{1}/{2}]'.format(sound.id, count + 1, len(sounds)))
    retrieve_sound_preview(sound, 'files/')

# Make a Pandas DataFrame with the metadata of our sound collection and save it
df =  pd.DataFrame([make_pandas_record(s) for s in sounds])
df.to_csv(DATAFRAME_FILENAME)
print('Saved DataFrame with {0} entries! {1}'.format(len(df), DATAFRAME_FILENAME))

# Show the contents of our DataFrame (the metadata of our source collection)
display(df)

Downloading sound with id 132584 [1/63]
Downloading sound with id 673512 [2/63]
Downloading sound with id 647617 [3/63]
Downloading sound with id 400707 [4/63]
Downloading sound with id 581461 [5/63]
Downloading sound with id 25634 [6/63]
Downloading sound with id 465547 [7/63]
Downloading sound with id 431636 [8/63]
Downloading sound with id 599886 [9/63]
Downloading sound with id 564190 [10/63]
Downloading sound with id 58481 [11/63]
Downloading sound with id 98259 [12/63]
Downloading sound with id 16290 [13/63]
Downloading sound with id 509486 [14/63]
Downloading sound with id 323619 [15/63]
Downloading sound with id 366400 [16/63]
Downloading sound with id 196758 [17/63]
Downloading sound with id 278173 [18/63]
Downloading sound with id 78567 [19/63]
Downloading sound with id 67407 [20/63]
Downloading sound with id 337873 [21/63]
Downloading sound with id 201094 [22/63]
Downloading sound with id 433742 [23/63]
Downloading sound with id 209942 [24/63]
Downloading sound with id 638643 [25/63]
Downloading sound with id 457041 [26/63]
Downloading sound with id 241648 [27/63]
Downloading sound with id 339946 [28/63]
Downloading sound with id 103342 [29/63]
Downloading sound with id 752904 [30/63]
Downloading sound with id 424343 [31/63]
Downloading sound with id 41114 [32/63]
Downloading sound with id 750917 [33/63]
Downloading sound with id 352760 [34/63]
Downloading sound with id 53371 [35/63]
Downloading sound with id 440395 [36/63]
Downloading sound with id 441529 [37/63]
Downloading sound with id 431944 [38/63]
Downloading sound with id 431231 [39/63]
Downloading sound with id 431284 [40/63]
Downloading sound with id 429083 [41/63]
Downloading sound with id 569850 [42/63]
Downloading sound with id 750915 [43/63]
Downloading sound with id 441348 [44/63]
Downloading sound with id 431249 [45/63]
Downloading sound with id 627753 [46/63]
Downloading sound with id 612195 [47/63]
Downloading sound with id 387188 [48/63]
Downloading sound with id 669733 [49/63]
Downloading sound with id 29568 [50/63]
Downloading sound with id 513398 [51/63]
Downloading sound with id 612218 [52/63]
Downloading sound with id 640033 [53/63]
Downloading sound with id 361267 [54/63]
Downloading sound with id 14517 [55/63]
Downloading sound with id 271079 [56/63]
Downloading sound with id 223834 [57/63]
Downloading sound with id 361262 [58/63]
Downloading sound with id 56808 [59/63]
Downloading sound with id 827848 [60/63]
Downloading sound with id 249592 [61/63]
Downloading sound with id 517297 [62/63]
Downloading sound with id 5567 [63/63]
Saved DataFrame with 63 entries! dataframe.csv

,name,username,license,tags,freesound_id,path
0,Kick Drum E-1,Rob10,http://creativecommons.org/publicdomain/zero/1.0/,"[Basic, Drum, Kick, one, sample, shot]",132584,files/132584_2409787-hq.ogg
1,Clicky Sub Kick Drum,TheEndOfACycle,http://creativecommons.org/publicdomain/zero/1.0/,"[1-hit, drum, drums, hit, kick, layered, one-s...",673512,files/673512_3130497-hq.ogg
2,Lo fi kick drum 01.wav,johnnypanic,http://creativecommons.org/publicdomain/zero/1.0/,"[drum, drums, kick, lofi, percussion, sample]",647617,files/647617_24119-hq.ogg
3,Subby Kick Drum,Mattc90,http://creativecommons.org/publicdomain/zero/1.0/,"[amazing, awesome, beat, bpm, campbell, cool, ...",400707,files/400707_1126957-hq.ogg
4,Fractanimal_Acoustic_Drum_Kit_Kick_7.wav,johnnydekk,http://creativecommons.org/publicdomain/zero/1.0/,"[drum, kick, kit, percussion]",581461,files/581461_5790048-hq.ogg
...,...,...,...,...,...,...
58,clap02.wav,esformouse,http://creativecommons.org/licenses/sampling+/...,"[clap, distortion, drum, electronic, percussio...",56808,files/56808_231832-hq.ogg
59,BleepdrumBD_02,oceansonmars,http://creativecommons.org/publicdomain/zero/1.0/,"[Analog, Bleep, Circuit-Bend, Clap, Drum, Drum...",827848,files/827848_15225418-hq.ogg
60,Dirty electro bass.wav,staticpony1,http://creativecommons.org/publicdomain/zero/1.0/,"[4x4-Records, Bass, Beat, Clap, Closed, Dance,...",249592,files/249592_4508519-hq.ogg
61,Trap Snare 2,muffin3k,http://creativecommons.org/publicdomain/zero/1.0/,"[drum, drums, hiphop, rap, sample, snare, trap]",517297,files/517297_10137963-hq.ogg
62,Attack Zound-155.wav,Jovica,https://creativecommons.org/licenses/by/4.0/,"[electronic, soundeffect]",5567,files/5567_2518-hq.ogg

## Collection 2: Piano Source

A contrasting source collection based on **piano sounds**.
Using piano as source for audio mosaicing produces very different results vs dark techno:
- Piano has wide timbral variety (notes, dynamics, attack/decay shapes)
- The contrast between techno target and piano source creates an experimental texture
- Comparing both collections is one of the key analyses for the report.

In [17]:
# ── Collection 2: Piano ───────────────────────────────────────────────────────
DATAFRAME_PIANO_FILENAME = 'dataframe_piano.csv'

piano_queries = [
    {'query': 'piano note single',  'filter': 'duration:[0 TO 3]', 'num_results': 20},
    {'query': 'piano chord',        'filter': 'duration:[0 TO 4]', 'num_results': 15},
    {'query': 'piano keys',         'filter': 'duration:[0 TO 2]', 'num_results': 15},
    {'query': 'piano low bass note','filter': 'duration:[0 TO 3]', 'num_results': 10},
]

piano_sounds = sum([
    query_freesound(q['query'], q['filter'], q['num_results'])
    for q in piano_queries
], [])

for count, sound in enumerate(piano_sounds):
    print(f'Downloading piano sound {sound.id} [{count+1}/{len(piano_sounds)}]')
    retrieve_sound_preview(sound, 'files/')

df_piano = pd.DataFrame([make_pandas_record(s) for s in piano_sounds])
df_piano.to_csv(DATAFRAME_PIANO_FILENAME)
print(f'Saved piano DataFrame with {len(df_piano)} entries → {DATAFRAME_PIANO_FILENAME}')
display(df_piano)

Downloading piano sound 740920 [1/43]
Downloading piano sound 315694 [2/43]
Downloading piano sound 795601 [3/43]
Downloading piano sound 794382 [4/43]
Downloading piano sound 448617 [5/43]
Downloading piano sound 161641 [6/43]
Downloading piano sound 25049 [7/43]
Downloading piano sound 314965 [8/43]
Downloading piano sound 155322 [9/43]
Downloading piano sound 52765 [10/43]
Downloading piano sound 631926 [11/43]
Downloading piano sound 386721 [12/43]
Downloading piano sound 577708 [13/43]
Downloading piano sound 112568 [14/43]
Downloading piano sound 467289 [15/43]
Downloading piano sound 488797 [16/43]
Downloading piano sound 488796 [17/43]
Downloading piano sound 488795 [18/43]
Downloading piano sound 488793 [19/43]
Downloading piano sound 488794 [20/43]
Downloading piano sound 322535 [21/43]
Downloading piano sound 827469 [22/43]
Downloading piano sound 148772 [23/43]
Downloading piano sound 447535 [24/43]
Downloading piano sound 632255 [25/43]
Downloading piano sound 372470 [26/43]
Downloading piano sound 578357 [27/43]
Downloading piano sound 448610 [28/43]
Downloading piano sound 634419 [29/43]
Downloading piano sound 409493 [30/43]
Downloading piano sound 409510 [31/43]
Downloading piano sound 409507 [32/43]
Downloading piano sound 409494 [33/43]
Downloading piano sound 409480 [34/43]
Downloading piano sound 409512 [35/43]
Downloading piano sound 409435 [36/43]
Downloading piano sound 127792 [37/43]
Downloading piano sound 630260 [38/43]
Downloading piano sound 795601 [39/43]
Downloading piano sound 680320 [40/43]
Downloading piano sound 148772 [41/43]
Downloading piano sound 713054 [42/43]
Downloading piano sound 22554 [43/43]
Saved piano DataFrame with 43 entries → dataframe_piano.csv

,name,username,license,tags,freesound_id,path
0,g6 note,rondindon,http://creativecommons.org/publicdomain/zero/1.0/,"[note, octave, piano, single, singlenote]",740920,files/740920_16083839-hq.ogg
1,Casio 1000P Preset - Piano C.wav,acollier123,https://creativecommons.org/licenses/by/4.0/,"[Additive, CT1000, Casio, casiotone, piano, sa...",315694,files/315694_2076119-hq.ogg
2,"Piano, C# -2, Muffled, Single Note",VizAion,http://creativecommons.org/publicdomain/zero/1.0/,"[Ab-note, Audio-Sample, Deep-sound, Keys, Musi...",795601,files/795601_17061405-hq.ogg
3,Upright Piano Remeau 23 C8,Sadiquecat,http://creativecommons.org/publicdomain/zero/1.0/,"[8, Average-piano, C, C8, FR-AV2, Living-room,...",794382,files/794382_5287430-hq.ogg
4,D7.ogg,TEDAgame,http://creativecommons.org/publicdomain/zero/1.0/,"[complete, keys, notes, old, piano, reverb, su...",448617,files/448617_9311684-hq.ogg
5,Slide Whistle in a Tin Can.wav,gurdonark,http://creativecommons.org/licenses/by/3.0/,"[mill, note, patch, piercing, sample, slide, s...",161641,files/161641_59021-hq.ogg
6,Kalimba_note4.wav,radian,http://creativecommons.org/licenses/by/3.0/,"[kalimba, metallic, thumb-piano]",25049,files/25049_76945-hq.ogg
7,Yamaha CS-30L - Toy Piano - C5 (Small Plick-72...,modularsamples,http://creativecommons.org/publicdomain/zero/1.0/,"[C5, Yamaha-CS-30L, midi-note-72, multisample,...",314965,files/314965_2050105-hq.ogg
8,Dog single howl,Jace,http://creativecommons.org/publicdomain/zero/1.0/,"[barking, beagle, dog, howl, nose, pooch, pupp...",155322,files/155322_60285-hq.ogg
9,"Vivace, con screamo - No Solo.wav",isaiah.chentnik,http://creativecommons.org/licenses/by/3.0/,"[bartok, chentnik, con, county, fair, isaiah, ...",52765,files/52765_634268-hq.ogg
10,Guitar string plucked at headstock,MathewHenry,http://creativecommons.org/publicdomain/zero/1.0/,"[guitar, instrument, one-shot, plucked, sample...",631926,files/631926_5544184-hq.ogg
11,Mi.WAV,LuckyLux,http://creativecommons.org/publicdomain/zero/1.0/,"[key, keyboard-notes, notes, piano-notes]",386721,files/386721_5999918-hq.ogg
12,Piano chord 1,mistakeless,http://creativecommons.org/licenses/by/3.0/,"[chord, chords, piano]",577708,files/577708_8000353-hq.ogg
13,piano F Minor chord.5th octave.wav,juskiddink,https://creativecommons.org/licenses/by/4.0/,"[acoustic, chord, dub, f, hit, minor, piano, r...",112568,files/112568_649468-hq.ogg
14,Dissonant Piano Stinger.mp3,XfiXy8,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, dissonant, piano, stinger, sudden]",467289,files/467289_9895957-hq.ogg
15,piano chord 8,PhonosUPF,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, piano, transformation]",488797,files/488797_10350281-hq.ogg
16,piano chord 7,PhonosUPF,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, piano, transformation]",488796,files/488796_10350281-hq.ogg
17,piano chord 6,PhonosUPF,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, piano, transformation]",488795,files/488795_10350281-hq.ogg
18,piano chord 4,PhonosUPF,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, piano, transformation]",488793,files/488793_10350281-hq.ogg
19,piano chord 5,PhonosUPF,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, piano, transformation]",488794,files/488794_10350281-hq.ogg
20,Two chords.wav,Fran89,http://creativecommons.org/licenses/by/3.0/,"[chord, chords, piano, sample, track]",322535,files/322535_4436764-hq.ogg
21,piano,jonahlpayne,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, keys, piano]",827469,files/827469_17908318-hq.ogg
22,piano_string_hit_short 5,Daphne_in_Wonderland,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, hammer, hand-inside, harp, hit, keys, ...",148772,files/148772_667113-hq.ogg
23,C MINOR CHORD.wav,djfroyd,http://creativecommons.org/licenses/by/3.0/,"[chord, cinematic, dramatic, film, finale, gro...",447535,files/447535_4766646-hq.ogg
24,Piano Bell Sound (C3).wav,Cloud-10,http://creativecommons.org/publicdomain/zero/1.0/,"[ambient, bass, bell, chord, electric, fender,...",632255,files/632255_10403690-hq.ogg
25,Piano B + 4th Chord,SSS_Samples,http://creativecommons.org/licenses/by/3.0/,"[Chord, Music-Based-on-Final-Fantasy, Piano, S...",372470,files/372470_5968459-hq.ogg
26,Dissonant Piano Sting 4,nomiqbomi,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, cinematic, creepy, dark, dissonant, dr...",578357,files/578357_10522382-hq.ogg
27,E7.ogg,TEDAgame,http://creativecommons.org/publicdomain/zero/1.0/,"[complete, keys, notes, old, piano, reverb, su...",448610,files/448610_9311684-hq.ogg
28,Usyd Piano Chords 34.wav,MGFaudio,http://creativecommons.org/publicdomain/zero/1.0/,"[chords, keys, piano]",634419,files/634419_4942436-hq.ogg
29,Piano.ff.F6-[AudioTrimmer.com].mp3,dwengomes,http://creativecommons.org/publicdomain/zero/1.0/,"[Keyboard, Keys, Piano]",409493,files/409493_7952991-hq.ogg
30,Piano.ff.B6-[AudioTrimmer.com].mp3,dwengomes,http://creativecommons.org/publicdomain/zero/1.0/,"[Keyboard, Keys, Piano]",409510,files/409510_7952991-hq.ogg
31,Piano.ff.A6-[AudioTrimmer.com].mp3,dwengomes,http://creativecommons.org/publicdomain/zero/1.0/,"[Keyboard, Keys, Piano]",409507,files/409507_7952991-hq.ogg
32,Piano.ff.G6-[AudioTrimmer.com].mp3,dwengomes,http://creativecommons.org/publicdomain/zero/1.0/,"[Keyboard, Keys, piano]",409494,files/409494_7952991-hq.ogg
33,Piano.ff.F6-[AudioTrimmer.com].mp3,dwengomes,http://creativecommons.org/publicdomain/zero/1.0/,"[Piano, keyboard, keys]",409480,files/409480_7952991-hq.ogg
34,Piano.ff.C7-[AudioTrimmer.com].mp3,dwengomes,http://creativecommons.org/publicdomain/zero/1.0/,"[Keyboard, Keys, Piano]",409512,files/409512_7952991-hq.ogg
35,Piano.mf.C6-[AudioTrimmer.com].mp3,dwengomes,http://creativecommons.org/publicdomain/zero/1.0/,"[keyboard, keys, piano]",409435,files/409435_7952991-hq.ogg
36,Pedal 03-16bit.wav,149203,http://creativecommons.org/publicdomain/zero/1.0/,"[ambience, background, bench, creaks, hammer, ...",127792,files/127792_1645805-hq.ogg
37,"Oddball Piano 002 Project (13,16 Time 170 BPM)...",Hewn.Marrow,https://creativecommons.org/licenses/by/4.0/,"[Angular, Angular-Rhythm, Angular-Rhythms, Key...",630260,files/630260_12333864-hq.ogg
38,"Piano, C# -2, Muffled, Single Note",VizAion,http://creativecommons.org/publicdomain/zero/1.0/,"[Ab-note, Audio-Sample, Deep-sound, Keys, Musi...",795601,files/795601_17061405-hq.ogg
39,Piano hit 2.wav,tur.kis,http://creativecommons.org/publicdomain/zero/1.0/,"[hammer, hit, keys, piano]",680320,files/680320_10399452-hq.ogg
40,piano_string_hit_short 5,Daphne_in_Wonderland,http://creativecommons.org/publicdomain/zero/1.0/,"[chord, hammer, hand-inside, harp, hit, keys, ...",148772,files/148772_667113-hq.ogg
41,Digital Mystery,4verage,http://creativecommons.org/publicdomain/zero/1.0/,"[digital, filter, keys, piano]",713054,files/713054_15473458-hq.ogg
42,BbStringHiG.wav,jdstarrett,https://creativecommons.org/licenses/by/4.0/,[contrabass],22554,files/22554_129507-hq.ogg